extends Node

var mini_names = [
	"Ahava İbrahim",
	"Aislin Arjun",
	"Alperen Laelius",
	"Alyssa Yohan",
	"Amatore Steffen",
	"Amun Polymnia",
	"Amyas Sonal",
	"Anil Yanna",
	"Arianrhod Mahulena",
	"Astra Mirjam",
	"Baha Andro",
	"Batul Elenora",
	"Binyamin Andromeda",
	"Brighid Magnus",
	"Brigid Olga",
	"Claude Celestino",
	"Cleophas Ferdinand",
	"Clotho Vidya",
	"Costas Sanjeet",
	"Da Saule",
	"Dalya Dinesha",
	"Damayanti Yavuz",
	"Dan Dimitra",
	"Darius Mariana",
	"Dinko Zoi",
	"Eachann Konstantin",
	"Eadric Zemfira",
	"Eifion Clementina",
	"Eulalia Zachariah",
	"Evgeni Krishna",
	"Faunus Marci",
	"Gai Niek",
	"Giada Hendrika",
	"Gilchrist Ragna",
	"Gisela Mireia",
	"Gus Ane",
	"Henrique Donat",
	"Heribert Takis",
	"Honorina Koba",
	"Honour Ilary",
	"Huang Herodotus",
	"Hudson Managold",
	"Ingvildr Awotwi",
	"Isabel Inaaya",
	"Izem Julián",
	"Jagannatha Adile",
	"Jayda Runa",
	"Jibril Magnhildr",
	"Jovan Menashsheh",
	"Juan Lina",
	"Judyta Leonora",
	"Junon Rolf",
	"Kalani Zhenya",
	"Kavita Bittor",
	"Kellie Ernest",
	"Kezia Anargul",
	"Korbin Hesiodos",
	"Kshitij Hilaria",
	"Kyung-Hee Samson",
	"Laelius Vasilii",
	"Lalita Roseanne",
	"Leif Iairos",
	"Lelio Trista",
	"Leonardo Montana",
	"Linnea Ola",
	"Lucky Walchelin",
	"Margit Almira",
	"Marie Hildur",
	"Marino Puk",
	"Maruf Mariamne",
	"Mele Yafa",
	"Miroslava Gwillym",
	"Ostap Setareh",
	"Palmiro Jozefa",
	"Phestos Rui",
	"Piero Motel",
	"Pradeep Dejan",
	"Praise Meliton",
	"Raj Rayen",
	"Rei Velasco",
	"Rizwana Andebert",
	"Rosa Amandine",
	"Rukmini Gautbert",
	"Shantanu Mandawuy",
	"Sharla Devadas",
	"Sjarel Akachi",
	"Skuld Shanta",
	"Teodora Isabella",
	"Thea Plato",
	"Thore Tatjana",
	"Tijana Lot",
	"Tiyamike Thor",
	"Tory Kgosi",
	"Vasudha Chidiebube",
	"Viivi Xaver",
	"Widogast Brajan",
	"Yama Sander",
	"Youcef Artemios",
	"Zephaniah Feroz",
	"Zlata Ste"
]

func mini_name():
	return mini_names[randi()%len(mini_names)]



var spell_names = [
	"Abjuration of Hysteria",
	"Acid Rupture",
	"Acid Spike",
	"Alteration Wave",
	"Ancestor's Beam",
	"Anger of Phantoms",
	"Annihilation of Life",
	"Ball of Soulpower",
	"Barrier of Twilight",
	"Blast of Life Draining",
	"Blast of Obliteration",
	"Blast of the Void",
	"Bolt of Atonement",
	"Burst of Agony",
	"Burst of Elemental Rage",
	"Charm of Clarity",
	"Conjuration of Faith",
	"Corruption Beam",
	"Curse",
	"Decadence of Hell",
	"Delay",
	"Deluge",
	"Demolition of Souls",
	"Dishonor of Confidence",
	"Distraction Curse",
	"Dragon Lash",
	"Dragon Nova",
	"Drain Life",
	"Drain Mana",
	"Ejection of Mana",
	"Elemental Frenzy",
	"Elemental Strike",
	"Enhance Spells",
	"Esoteric Blaze",
	"Evocation of Death",
	"Evocation of Heat",
	"Evocation of Phantoms",
	"Execute",
	"Extortion of Sight",
	"Fire Burst",
	"Fire Fingers",
	"Fire Orb",
	"Flare of Control",
	"Flourish",
	"Force Aura",
	"Frost Spike",
	"Hellfire Torrent",
	"Holy Flux",
	"Ice Orb",
	"Illusion",
	"Illusion of Blessings",
	"Incantation of Dragons",
	"Incinerate",
	"Jinx of Acid",
	"Jinx of Demon Fire",
	"Jinx of Serendipity",
	"Lunar Beam",
	"Mage Charge",
	"Mage Volley",
	"Magma Bomb",
	"Magma Eruption",
	"Magma Rush",
	"Manifest Soul",
	"Minimize",
	"Molten Rain",
	"Mystic Rocket",
	"Nature's Oath",
	"Negation of Force",
	"Nether Surge",
	"Nether Tempest",
	"Orb of Arcane Energy",
	"Paralyzing of Rituals",
	"Plagueing Flarex",
	"Projection of Heaven",
	"Protection Bolt",
	"Purge",
	"Rain of Contagion",
	"Rain of Fire",
	"Reanimate Corpse",
	"Restrict",
	"Restrict Movement",
	"Sanctity of Insanity",
	"Seal of Darkness",
	"Solitude of Ecstasy",
	"Solitude of Energy",
	"Soul Frenzy",
	"Spell of Punishment",
	"Spellshield of Shadows",
	"Sunlight Bomb",
	"Sunlight Nova",
	"Sunlight Surge",
	"Thunder Rain",
	"Transform",
	"Victory of Armor",
	"Virtue of Knowledge",
	"Vision of Sealing",
	"Void of Stamina",
	"Wave of Contagion",
	"Wind Frenzy",
	"Wrath of Doom"
]

func spell_name():
	return spell_names[randi()%len(spell_names)]
